using Microsoft.UI.Xaml;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace AppMovil.WinUI
{
    /// <summary>
    /// Provides application-specific behavior to supplement the default Application class.
    /// </summary>
    public partial class App : MauiWinUIApplication
    {
        // InitializeComponent is generated by XAML build tasks for WinUI; do not redefine it here.
        /// <summary>
        /// Initializes the singleton application object.  This is the first line of authored code
        /// executed, and as such is the logical equivalent of main() or WinMain().
        /// </summary>
        public App()
        {
            this.InitializeComponent();

            // Manejador global de excepciones para evitar que la app se detenga
            Microsoft.UI.Xaml.Application.Current.UnhandledException += (sender, e) =>
            {
                try
                {
                    var details = $"UnhandledException: {e.Message} - {e.Exception}\r\n{e.Exception?.StackTrace}";
                    System.Diagnostics.Debug.WriteLine(details);
                    var folder = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
                    var file = System.IO.Path.Combine(folder, "AppMovil-unhandled-exception.txt");
                    System.IO.File.AppendAllText(file, DateTime.Now + " - " + details + "\r\n\r\n");
                }
                catch { }
                e.Handled = true; // forzar manejo para que no aparezca el cuadro de JIT
            };

            // Captura excepciones no observadas de tareas para evitar cierre/JIT
            System.Threading.Tasks.TaskScheduler.UnobservedTaskException += (s, e) =>
            {
                e.SetObserved();
            };
            AppDomain.CurrentDomain.FirstChanceException += (s, e) =>
            {
                try
                {
                    var details = $"FirstChanceException: {e.Exception?.GetType()} - {e.Exception?.Message}\r\n{e.Exception?.StackTrace}";
                    System.Diagnostics.Debug.WriteLine(details);
                    var folder = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
                    var file = System.IO.Path.Combine(folder, "AppMovil-firstchance-exceptions.log");
                    System.IO.File.AppendAllText(file, DateTime.Now + " - " + details + "\r\n\r\n");
                }
                catch { }
                // No interrumpir, solo dejar trazas si fuera necesario
            };
        }

        protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
    }

}
